INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("1","18/08/2017","1","Bayern München","Bayer Leverkusen","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("2","19/08/2017","1","1899 Hoffenheim","Werder Bremen","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("3","19/08/2017","1","Hertha BSC","VfB Stuttgart","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("4","19/08/2017","1","Hamburger SV","FC Augsburg","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("5","19/08/2017","1","1. FSV Mainz 05","Hannover 96","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("6","19/08/2017","1","VfL Wolfsburg","Borussia Dortmund","0","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("7","19/08/2017","1","FC Schalke 04","RB Leipzig","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("8","20/08/2017","1","SC Freiburg","Eintracht Frankfurt","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("9","20/08/2017","1","Bor. Mönchengladbach","1. FC Köln","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("10","25/08/2017","2","1. FC Köln","Hamburger SV","1","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("11","26/08/2017","2","Werder Bremen","Bayern München","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("12","26/08/2017","2","Eintracht Frankfurt","VfL Wolfsburg","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("13","26/08/2017","2","Bayer Leverkusen","1899 Hoffenheim","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("14","26/08/2017","2","FC Augsburg","Bor. Mönchengladbach","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("15","26/08/2017","2","VfB Stuttgart","1. FSV Mainz 05","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("16","26/08/2017","2","Borussia Dortmund","Hertha BSC","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("17","27/08/2017","2","RB Leipzig","SC Freiburg","4","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("18","27/08/2017","2","Hannover 96","FC Schalke 04","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("19","08/09/2017","3","Hamburger SV","RB Leipzig","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("20","09/09/2017","3","SC Freiburg","Borussia Dortmund","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("21","09/09/2017","3","Bor. Mönchengladbach","Eintracht Frankfurt","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("22","09/09/2017","3","FC Augsburg","1. FC Köln","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("23","09/09/2017","3","1. FSV Mainz 05","Bayer Leverkusen","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("24","09/09/2017","3","VfL Wolfsburg","Hannover 96","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("25","09/09/2017","3","1899 Hoffenheim","Bayern München","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("26","10/09/2017","3","Hertha BSC","Werder Bremen","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("27","10/09/2017","3","FC Schalke 04","VfB Stuttgart","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("28","15/09/2017","4","Hannover 96","Hamburger SV","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("29","16/09/2017","4","Bayern München","1. FSV Mainz 05","4","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("30","16/09/2017","4","Werder Bremen","FC Schalke 04","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("31","16/09/2017","4","Eintracht Frankfurt","FC Augsburg","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("32","16/09/2017","4","VfB Stuttgart","VfL Wolfsburg","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("33","16/09/2017","4","RB Leipzig","Bor. Mönchengladbach","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("34","17/09/2017","4","1899 Hoffenheim","Hertha BSC","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("35","17/09/2017","4","Bayer Leverkusen","SC Freiburg","4","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("36","17/09/2017","4","Borussia Dortmund","1. FC Köln","5","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("37","19/09/2017","5","Bor. Mönchengladbach","VfB Stuttgart","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("38","19/09/2017","5","FC Schalke 04","Bayern München","0","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("39","19/09/2017","5","FC Augsburg","RB Leipzig","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("40","19/09/2017","5","VfL Wolfsburg","Werder Bremen","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("41","20/09/2017","5","1. FC Köln","Eintracht Frankfurt","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("42","20/09/2017","5","Hertha BSC","Bayer Leverkusen","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("43","20/09/2017","5","SC Freiburg","Hannover 96","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("44","20/09/2017","5","Hamburger SV","Borussia Dortmund","0","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("45","20/09/2017","5","1. FSV Mainz 05","1899 Hoffenheim","2","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("46","22/09/2017","6","Bayern München","VfL Wolfsburg","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("47","23/09/2017","6","RB Leipzig","Eintracht Frankfurt","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("48","23/09/2017","6","1899 Hoffenheim","FC Schalke 04","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("49","23/09/2017","6","Werder Bremen","SC Freiburg","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("50","23/09/2017","6","1. FSV Mainz 05","Hertha BSC","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("51","23/09/2017","6","VfB Stuttgart","FC Augsburg","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("52","23/09/2017","6","Borussia Dortmund","Bor. Mönchengladbach","6","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("53","24/09/2017","6","Hannover 96","1. FC Köln","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("54","24/09/2017","6","Bayer Leverkusen","Hamburger SV","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("55","29/09/2017","7","FC Schalke 04","Bayer Leverkusen","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("56","30/09/2017","7","Eintracht Frankfurt","VfB Stuttgart","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("57","30/09/2017","7","FC Augsburg","Borussia Dortmund","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("58","30/09/2017","7","VfL Wolfsburg","1. FSV Mainz 05","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("59","30/09/2017","7","Bor. Mönchengladbach","Hannover 96","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("60","30/09/2017","7","Hamburger SV","Werder Bremen","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("61","01/10/2017","7","SC Freiburg","1899 Hoffenheim","3","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("62","01/10/2017","7","Hertha BSC","Bayern München","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("63","01/10/2017","7","1. FC Köln","RB Leipzig","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("64","13/10/2017","8","VfB Stuttgart","1. FC Köln","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("65","14/10/2017","8","Bayern München","SC Freiburg","5","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("66","14/10/2017","8","1899 Hoffenheim","FC Augsburg","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("67","14/10/2017","8","Hertha BSC","FC Schalke 04","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("68","14/10/2017","8","1. FSV Mainz 05","Hamburger SV","3","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("69","14/10/2017","8","Hannover 96","Eintracht Frankfurt","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("70","14/10/2017","8","Borussia Dortmund","RB Leipzig","2","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("71","15/10/2017","8","Bayer Leverkusen","VfL Wolfsburg","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("72","15/10/2017","8","Werder Bremen","Bor. Mönchengladbach","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("73","20/10/2017","9","FC Schalke 04","1. FSV Mainz 05","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("74","21/10/2017","9","RB Leipzig","VfB Stuttgart","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("75","21/10/2017","9","Bor. Mönchengladbach","Bayer Leverkusen","1","5");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("76","21/10/2017","9","Eintracht Frankfurt","Borussia Dortmund","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("77","21/10/2017","9","FC Augsburg","Hannover 96","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("78","21/10/2017","9","Hamburger SV","Bayern München","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("79","22/10/2017","9","1. FC Köln","Werder Bremen","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("80","22/10/2017","9","SC Freiburg","Hertha BSC","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("81","22/10/2017","9","VfL Wolfsburg","1899 Hoffenheim","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("82","27/10/2017","10","1. FSV Mainz 05","Eintracht Frankfurt","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("83","28/10/2017","10","1899 Hoffenheim","Bor. Mönchengladbach","1","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("84","28/10/2017","10","Hertha BSC","Hamburger SV","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("85","28/10/2017","10","FC Schalke 04","VfL Wolfsburg","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("86","28/10/2017","10","Bayer Leverkusen","1. FC Köln","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("87","28/10/2017","10","Hannover 96","Borussia Dortmund","4","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("88","28/10/2017","10","Bayern München","RB Leipzig","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("89","29/10/2017","10","Werder Bremen","FC Augsburg","0","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("90","29/10/2017","10","VfB Stuttgart","SC Freiburg","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("91","03/11/2017","11","Eintracht Frankfurt","Werder Bremen","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("92","04/11/2017","11","RB Leipzig","Hannover 96","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("93","04/11/2017","11","SC Freiburg","FC Schalke 04","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("94","04/11/2017","11","Bor. Mönchengladbach","1. FSV Mainz 05","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("95","04/11/2017","11","FC Augsburg","Bayer Leverkusen","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("96","04/11/2017","11","Hamburger SV","VfB Stuttgart","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("97","04/11/2017","11","Borussia Dortmund","Bayern München","1","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("98","05/11/2017","11","1. FC Köln","1899 Hoffenheim","0","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("99","05/11/2017","11","VfL Wolfsburg","Hertha BSC","3","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("100","17/11/2017","12","VfB Stuttgart","Borussia Dortmund","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("101","18/11/2017","12","Bayern München","FC Augsburg","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("102","18/11/2017","12","1899 Hoffenheim","Eintracht Frankfurt","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("103","18/11/2017","12","Bayer Leverkusen","RB Leipzig","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("104","18/11/2017","12","1. FSV Mainz 05","1. FC Köln","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("105","18/11/2017","12","VfL Wolfsburg","SC Freiburg","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("106","18/11/2017","12","Hertha BSC","Bor. Mönchengladbach","2","4");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("107","19/11/2017","12","FC Schalke 04","Hamburger SV","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("108","19/11/2017","12","Werder Bremen","Hannover 96","4","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("109","24/11/2017","13","Hannover 96","VfB Stuttgart","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("110","25/11/2017","13","Borussia Dortmund","FC Schalke 04","4","4");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("111","25/11/2017","13","RB Leipzig","Werder Bremen","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("112","25/11/2017","13","SC Freiburg","1. FSV Mainz 05","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("113","25/11/2017","13","Eintracht Frankfurt","Bayer Leverkusen","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("114","25/11/2017","13","FC Augsburg","VfL Wolfsburg","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("115","25/11/2017","13","Bor. Mönchengladbach","Bayern München","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("116","26/11/2017","13","Hamburger SV","1899 Hoffenheim","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("117","26/11/2017","13","1. FC Köln","Hertha BSC","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("118","01/12/2017","14","SC Freiburg","Hamburger SV","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("119","02/12/2017","14","Bayern München","Hannover 96","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("120","02/12/2017","14","1899 Hoffenheim","RB Leipzig","4","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("121","02/12/2017","14","Werder Bremen","VfB Stuttgart","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("122","02/12/2017","14","Bayer Leverkusen","Borussia Dortmund","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("123","02/12/2017","14","1. FSV Mainz 05","FC Augsburg","1","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("124","02/12/2017","14","FC Schalke 04","1. FC Köln","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("125","03/12/2017","14","Hertha BSC","Eintracht Frankfurt","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("126","03/12/2017","14","VfL Wolfsburg","Bor. Mönchengladbach","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("127","08/12/2017","15","VfB Stuttgart","Bayer Leverkusen","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("128","09/12/2017","15","Borussia Dortmund","Werder Bremen","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("129","09/12/2017","15","RB Leipzig","1. FSV Mainz 05","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("130","09/12/2017","15","Eintracht Frankfurt","Bayern München","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("131","09/12/2017","15","Hamburger SV","VfL Wolfsburg","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("132","09/12/2017","15","Bor. Mönchengladbach","FC Schalke 04","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("133","10/12/2017","15","1. FC Köln","SC Freiburg","3","4");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("134","10/12/2017","15","Hannover 96","1899 Hoffenheim","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("135","10/12/2017","15","FC Augsburg","Hertha BSC","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("136","12/12/2017","16","VfL Wolfsburg","RB Leipzig","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("137","12/12/2017","16","Hamburger SV","Eintracht Frankfurt","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("138","12/12/2017","16","1. FSV Mainz 05","Borussia Dortmund","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("139","12/12/2017","16","SC Freiburg","Bor. Mönchengladbach","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("140","13/12/2017","16","1899 Hoffenheim","VfB Stuttgart","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("141","13/12/2017","16","Bayern München","1. FC Köln","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("142","13/12/2017","16","Hertha BSC","Hannover 96","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("143","13/12/2017","16","FC Schalke 04","FC Augsburg","3","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("144","13/12/2017","16","Bayer Leverkusen","Werder Bremen","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("145","15/12/2017","17","Bor. Mönchengladbach","Hamburger SV","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("146","16/12/2017","17","1. FC Köln","VfL Wolfsburg","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("147","16/12/2017","17","Werder Bremen","1. FSV Mainz 05","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("148","16/12/2017","17","Eintracht Frankfurt","FC Schalke 04","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("149","16/12/2017","17","FC Augsburg","SC Freiburg","3","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("150","16/12/2017","17","VfB Stuttgart","Bayern München","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("151","16/12/2017","17","Borussia Dortmund","1899 Hoffenheim","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("152","17/12/2017","17","Hannover 96","Bayer Leverkusen","4","4");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("153","17/12/2017","17","RB Leipzig","Hertha BSC","2","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("154","12/01/2018","18","Bayer Leverkusen","Bayern München","1","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("155","13/01/2018","18","Werder Bremen","1899 Hoffenheim","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("156","13/01/2018","18","VfB Stuttgart","Hertha BSC","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("157","13/01/2018","18","Eintracht Frankfurt","SC Freiburg","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("158","13/01/2018","18","FC Augsburg","Hamburger SV","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("159","13/01/2018","18","Hannover 96","1. FSV Mainz 05","3","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("160","13/01/2018","18","RB Leipzig","FC Schalke 04","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("161","14/01/2018","18","1. FC Köln","Bor. Mönchengladbach","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("162","14/01/2018","18","Borussia Dortmund","VfL Wolfsburg","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("163","19/01/2018","19","Hertha BSC","Borussia Dortmund","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("164","20/01/2018","19","SC Freiburg","RB Leipzig","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("165","20/01/2018","19","VfL Wolfsburg","Eintracht Frankfurt","1","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("166","20/01/2018","19","1899 Hoffenheim","Bayer Leverkusen","1","4");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("167","20/01/2018","19","Bor. Mönchengladbach","FC Augsburg","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("168","20/01/2018","19","1. FSV Mainz 05","VfB Stuttgart","3","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("169","20/01/2018","19","Hamburger SV","1. FC Köln","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("170","21/01/2018","19","Bayern München","Werder Bremen","4","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("171","21/01/2018","19","FC Schalke 04","Hannover 96","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("172","26/01/2018","20","Eintracht Frankfurt","Bor. Mönchengladbach","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("173","27/01/2018","20","Bayern München","1899 Hoffenheim","5","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("174","27/01/2018","20","Borussia Dortmund","SC Freiburg","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("175","27/01/2018","20","VfB Stuttgart","FC Schalke 04","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("176","27/01/2018","20","1. FC Köln","FC Augsburg","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("177","27/01/2018","20","RB Leipzig","Hamburger SV","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("178","27/01/2018","20","Werder Bremen","Hertha BSC","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("179","28/01/2018","20","Bayer Leverkusen","1. FSV Mainz 05","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("180","28/01/2018","20","Hannover 96","VfL Wolfsburg","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("181","02/02/2018","21","1. FC Köln","Borussia Dortmund","2","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("182","03/02/2018","21","1. FSV Mainz 05","Bayern München","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("183","03/02/2018","21","Hertha BSC","1899 Hoffenheim","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("184","03/02/2018","21","FC Schalke 04","Werder Bremen","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("185","03/02/2018","21","SC Freiburg","Bayer Leverkusen","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("186","03/02/2018","21","VfL Wolfsburg","VfB Stuttgart","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("187","03/02/2018","21","Bor. Mönchengladbach","RB Leipzig","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("188","04/02/2018","21","FC Augsburg","Eintracht Frankfurt","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("189","04/02/2018","21","Hamburger SV","Hannover 96","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("190","09/02/2018","22","RB Leipzig","FC Augsburg","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("191","10/02/2018","22","Eintracht Frankfurt","1. FC Köln","4","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("192","10/02/2018","22","Bayer Leverkusen","Hertha BSC","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("193","10/02/2018","22","Hannover 96","SC Freiburg","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("194","10/02/2018","22","Borussia Dortmund","Hamburger SV","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("195","10/02/2018","22","1899 Hoffenheim","1. FSV Mainz 05","4","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("196","10/02/2018","22","Bayern München","FC Schalke 04","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("197","11/02/2018","22","VfB Stuttgart","Bor. Mönchengladbach","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("198","11/02/2018","22","Werder Bremen","VfL Wolfsburg","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("199","16/02/2018","23","Hertha BSC","1. FSV Mainz 05","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("200","17/02/2018","23","VfL Wolfsburg","Bayern München","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("201","17/02/2018","23","SC Freiburg","Werder Bremen","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("202","17/02/2018","23","Hamburger SV","Bayer Leverkusen","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("203","17/02/2018","23","1. FC Köln","Hannover 96","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("204","17/02/2018","23","FC Schalke 04","1899 Hoffenheim","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("205","18/02/2018","23","FC Augsburg","VfB Stuttgart","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("206","18/02/2018","23","Bor. Mönchengladbach","Borussia Dortmund","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("207","19/02/2018","23","Eintracht Frankfurt","RB Leipzig","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("208","23/02/2018","24","1. FSV Mainz 05","VfL Wolfsburg","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("209","24/02/2018","24","Bayern München","Hertha BSC","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("210","24/02/2018","24","1899 Hoffenheim","SC Freiburg","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("211","24/02/2018","24","Hannover 96","Bor. Mönchengladbach","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("212","24/02/2018","24","VfB Stuttgart","Eintracht Frankfurt","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("213","24/02/2018","24","Werder Bremen","Hamburger SV","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("214","25/02/2018","24","Bayer Leverkusen","FC Schalke 04","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("215","25/02/2018","24","RB Leipzig","1. FC Köln","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("216","26/02/2018","24","Borussia Dortmund","FC Augsburg","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("217","02/03/2018","25","Bor. Mönchengladbach","Werder Bremen","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("218","03/03/2018","25","FC Schalke 04","Hertha BSC","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("219","03/03/2018","25","Eintracht Frankfurt","Hannover 96","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("220","03/03/2018","25","FC Augsburg","1899 Hoffenheim","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("221","03/03/2018","25","Hamburger SV","1. FSV Mainz 05","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("222","03/03/2018","25","VfL Wolfsburg","Bayer Leverkusen","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("223","03/03/2018","25","RB Leipzig","Borussia Dortmund","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("224","04/03/2018","25","1. FC Köln","VfB Stuttgart","2","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("225","04/03/2018","25","SC Freiburg","Bayern München","0","4");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("226","09/03/2018","26","1. FSV Mainz 05","FC Schalke 04","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("227","10/03/2018","26","Hertha BSC","SC Freiburg","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("228","10/03/2018","26","Hannover 96","FC Augsburg","1","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("229","10/03/2018","26","Bayern München","Hamburger SV","6","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("230","10/03/2018","26","1899 Hoffenheim","VfL Wolfsburg","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("231","10/03/2018","26","Bayer Leverkusen","Bor. Mönchengladbach","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("232","11/03/2018","26","VfB Stuttgart","RB Leipzig","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("233","11/03/2018","26","Borussia Dortmund","Eintracht Frankfurt","3","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("234","12/03/2018","26","Werder Bremen","1. FC Köln","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("235","16/03/2018","27","SC Freiburg","VfB Stuttgart","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("236","17/03/2018","27","Bor. Mönchengladbach","1899 Hoffenheim","3","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("237","17/03/2018","27","Hamburger SV","Hertha BSC","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("238","17/03/2018","27","FC Augsburg","Werder Bremen","1","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("239","17/03/2018","27","Eintracht Frankfurt","1. FSV Mainz 05","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("240","17/03/2018","27","VfL Wolfsburg","FC Schalke 04","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("241","18/03/2018","27","Borussia Dortmund","Hannover 96","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("242","18/03/2018","27","1. FC Köln","Bayer Leverkusen","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("243","18/03/2018","27","RB Leipzig","Bayern München","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("244","31/03/2018","28","Hannover 96","RB Leipzig","2","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("245","31/03/2018","28","1899 Hoffenheim","1. FC Köln","6","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("246","31/03/2018","28","FC Schalke 04","SC Freiburg","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("247","31/03/2018","28","Bayer Leverkusen","FC Augsburg","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("248","31/03/2018","28","VfB Stuttgart","Hamburger SV","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("249","31/03/2018","28","Bayern München","Borussia Dortmund","6","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("250","31/03/2018","28","Hertha BSC","VfL Wolfsburg","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("251","01/04/2018","28","Werder Bremen","Eintracht Frankfurt","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("252","01/04/2018","28","1. FSV Mainz 05","Bor. Mönchengladbach","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("253","06/04/2018","29","Hannover 96","Werder Bremen","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("254","07/04/2018","29","FC Augsburg","Bayern München","1","4");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("255","07/04/2018","29","Bor. Mönchengladbach","Hertha BSC","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("256","07/04/2018","29","1. FC Köln","1. FSV Mainz 05","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("257","07/04/2018","29","SC Freiburg","VfL Wolfsburg","0","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("258","07/04/2018","29","Hamburger SV","FC Schalke 04","3","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("259","08/04/2018","29","Borussia Dortmund","VfB Stuttgart","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("260","08/04/2018","29","Eintracht Frankfurt","1899 Hoffenheim","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("261","13/04/2018","30","VfL Wolfsburg","FC Augsburg","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("262","14/04/2018","30","Hertha BSC","1. FC Köln","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("263","14/04/2018","30","Bayer Leverkusen","Eintracht Frankfurt","4","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("264","14/04/2018","30","1899 Hoffenheim","Hamburger SV","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("265","14/04/2018","30","VfB Stuttgart","Hannover 96","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("266","14/04/2018","30","Bayern München","Bor. Mönchengladbach","5","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("267","15/04/2018","30","FC Schalke 04","Borussia Dortmund","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("268","15/04/2018","30","Werder Bremen","RB Leipzig","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("269","16/04/2018","30","1. FSV Mainz 05","SC Freiburg","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("270","20/04/2018","31","Bor. Mönchengladbach","VfL Wolfsburg","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("271","21/04/2018","31","Hannover 96","Bayern München","0","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("272","21/04/2018","31","RB Leipzig","1899 Hoffenheim","2","5");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("273","21/04/2018","31","Eintracht Frankfurt","Hertha BSC","0","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("274","21/04/2018","31","Hamburger SV","SC Freiburg","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("275","22/04/2018","31","VfB Stuttgart","Werder Bremen","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("276","22/04/2018","31","Borussia Dortmund","Bayer Leverkusen","4","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("277","22/04/2018","31","FC Augsburg","1. FSV Mainz 05","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("278","22/04/2018","31","1. FC Köln","FC Schalke 04","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("279","27/04/2018","32","1899 Hoffenheim","Hannover 96","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("280","28/04/2018","32","SC Freiburg","1. FC Köln","3","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("281","28/04/2018","32","FC Schalke 04","Bor. Mönchengladbach","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("282","28/04/2018","32","Bayern München","Eintracht Frankfurt","4","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("283","28/04/2018","32","Hertha BSC","FC Augsburg","2","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("284","28/04/2018","32","VfL Wolfsburg","Hamburger SV","1","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("285","28/04/2018","32","Bayer Leverkusen","VfB Stuttgart","0","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("286","29/04/2018","32","1. FSV Mainz 05","RB Leipzig","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("287","29/04/2018","32","Werder Bremen","Borussia Dortmund","1","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("288","05/05/2018","33","1. FC Köln","Bayern München","1","3");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("289","05/05/2018","33","VfB Stuttgart","1899 Hoffenheim","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("291","05/05/2018","33","Hannover 96","Hertha BSC","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("292","05/05/2018","33","Bor. Mönchengladbach","SC Freiburg","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("293","05/05/2018","33","FC Augsburg","FC Schalke 04","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("294","05/05/2018","33","Werder Bremen","Bayer Leverkusen","0","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("295","05/05/2018","33","Eintracht Frankfurt","Hamburger SV","3","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("296","05/05/2018","33","Borussia Dortmund","1. FSV Mainz 05","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("297","05/05/2018","33","RB Leipzig","VfL Wolfsburg","4","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("298","09/04/2018","29","RB Leipzig","Bayer Leverkusen","1","4");

INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("299","12/05/2018","34","1899 Hoffenheim","Borussia Dortmund","3","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("300","12/05/2018","34","Hertha BSC","RB Leipzig","2","6");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("301","12/05/2018","34","VfL Wolfsburg","1. FC Köln","4","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("302","12/05/2018","34","1. FSV Mainz 05","Werder Bremen","1","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("303","12/05/2018","34","Hamburger SV","Bor. Mönchengladbach","2","1");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("304","12/05/2018","34","FC Schalke 04","Eintracht Frankfurt","1","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("305","12/05/2018","34","SC Freiburg","FC Augsburg","2","0");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("306","12/05/2018","34","Bayer Leverkusen","Hannover 96","3","2");
INSERT INTO partidos (Id, Fecha, Jornada,  Local, Visita, GolesLocal, GolesVisita) VALUES ("307","12/05/2018","34","Bayern München","VfB Stuttgart","1","4");
